# Generated by Django 2.2.19 on 2023-06-17 10:48

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='пароль')),
                ('first_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=150, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=150, verbose_name='имя')),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('man', 'мужской'), ('woman', 'женский')], help_text='укажите пол пациента.', max_length=10, verbose_name='пол')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="введите номер телефона в формате: '+7xxxxxxxxxx'", regex='^\\+7\\d{9,14}$')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('admin', 'Администратор')], default='user', help_text='Администратор или Аутентифицированный пользователь.По умолчанию `user`.', max_length=33, verbose_name='пользовательская роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
